### ISSUE TITLE
Comet Cache replacement - std or Pro?

### ISSUE THREAD

**Issue by jcamp** [megaoptim/rapid-cache#4]
Does this now effectively replace the comet cache standard or the PRO version...?

**Comment by gdarko** [comment]
@jcamp It replaces the standard version and is not compatible with the PRO version.

**Comment by jcamp** [comment]
Are you doing a 'Pro' version?

**Comment by gdarko** [comment]
I am working on a paid version of this plugin however I don't have eta for now.

Feel free to send any feature requests at info@megaoptim.com
