### ISSUE TITLE
Messages doesn't go away with (x)

### ISSUE THREAD

**Issue by dimalif** [megaoptim/rapid-cache#7]
This can't be closed for some reason. Wordpress 5.6 and 5.7.
![2021-03-21 22_28_47-Window](https://user-images.githubusercontent.com/53921528/111920038-6f7aa180-8a95-11eb-90d2-629ebba7350a.png)

**Comment by dimalif** [comment]
I mean it goes away only if your refresh. You can't close it.

**Comment by gdarko** [comment]
Hey @dimalif ,

The issue has been resolved in v1.2.2.

Best Regards,
Darko
