### ISSUE TITLE
fatal error right after activation

### ISSUE THREAD

**Issue by Presskopp** [megaoptim/rapid-cache#9]
running a local installation with WP 5.8-alpha-50561 and PHP 8:

Fatal error: Uncaught Error: Call to undefined function MegaOptim\RapidCache\Traits\Shared\create_function() in C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Shared\FsUtils.php:40 Stack trace: #0 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Shared\FsUtils.php(94): MegaOptim\RapidCache\Classes\AbsBaseAp->nDirSeps('C:\\Users\\CHRIST...') #1 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Shared\CacheLockUtils.php(53): MegaOptim\RapidCache\Classes\AbsBaseAp->getTmpDir() #2 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Plugin\InstallUtils.php(354): MegaOptim\RapidCache\Classes\AbsBaseAp->cacheLock() #3 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Plugin\OptionUtils.php(155): MegaOptim\RapidCache\Classes\Plugin->addAdvancedCache() #4 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Classes\Actions.php(336): MegaOptim\RapidCache\Classes\Plugin->refreshAfterOptionsUpdate(Array) #5 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Classes\Actions.php(55): MegaOptim\RapidCache\Classes\Actions->saveOptions(Array) #6 C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Plugin\ActionUtils.php(25): MegaOptim\RapidCache\Classes\Actions->__construct() #7 C:\Users\Christian\Local Sites\dev\app\public\wp-includes\class-wp-hook.php(292): MegaOptim\RapidCache\Classes\Plugin->actions('') #8 C:\Users\Christian\Local Sites\dev\app\public\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #9 C:\Users\Christian\Local Sites\dev\app\public\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #10 C:\Users\Christian\Local Sites\dev\app\public\wp-settings.php(582): do_action('wp_loaded') #11 C:\Users\Christian\Local Sites\dev\app\public\wp-config.php(75): require_once('C:\\Users\\Christ...') #12 C:\Users\Christian\Local Sites\dev\app\public\wp-load.php(44): require_once('C:\\Users\\Christ...') #13 C:\Users\Christian\Local Sites\dev\app\public\wp-admin\admin.php(34): require_once('C:\\Users\\Christ...') #14 {main} thrown in C:\Users\Christian\Local Sites\dev\app\public\wp-content\plugins\rapid-cache\includes\src\Traits\Shared\FsUtils.php on line 40

**Comment by gdarko** [comment]
The issue was fixed in SHA-c673c273226aa8569cf4d56c285fad45fd84f9f1
